version: '3'
services:
  # Mysql サーバを起動するコンテナ
  mysql:
    image: mysql
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - '3306:3306'
  # Selenium サーバを起動するコンテナ
  selenium:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium
    ports:
      # Selenium サーバに接続するポート
      - "4444:4444"
      # VNC で接続するポート
      - "5900:5900"
      # Selenium サーバのログを出力するポート
      - "7900:7900"
    # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    env_file:
      - .env
    tty: true
    volumes:
      - ./:/root/opt